apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: nist-mirror
  name: nist-mirror-cm
data:
  mirror.conf: |
    server {
        listen 80;
        server_name _REPLACEME_;

        client_max_body_size 25M;

        root /var/www;
    }
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $host - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for" '
                          '- $request_time $upstream_response_time $pipe';

        access_log  /var/log/nginx/access.log  main;

        server_tokens off;

        proxy_buffer_size   128k;
        proxy_buffers   8 256k;
        proxy_busy_buffers_size   256k;

        sendfile        on;
        keepalive_timeout  65;
        include /etc/nginx/conf.d/mirror.conf;
    }
