apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: nist-mirror
  name: nist-mirror-fetcher-cronjob
spec:
  schedule: "15 6 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: nist-mirror-fetcher-img
              image: _REPLACEME_/nist-mirror-fetcher:latest
              command:
                - /app/mirror.sh
              imagePullPolicy: Always
              env:
                - name: NVD_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: nist-mirror-fetcher-secret
                      key: NVD_API_KEY
              resources:
                limits:
                  cpu: 1
                  memory: 3Gi
                requests:
                  cpu: 500m
                  memory: 3Gi
              volumeMounts:
                - mountPath: /var/www
                  name: volume-mirror-data
          restartPolicy: Never
          volumes:
            - name: volume-mirror-data
              persistentVolumeClaim:
                claimName: nist-mirror-cache-pvc
