apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nist-mirror-cache-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-storageclass
